"""empty message

Revision ID: 04674a5a99d3
Revises: cc295e2f5241
Create Date: 2019-06-27 23:00:17.604428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04674a5a99d3'
down_revision = 'cc295e2f5241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address', table_name='person')
    op.drop_index('city', table_name='person')
    op.drop_index('last_name', table_name='person')
    op.drop_index('name', table_name='person')
    op.drop_index('password', table_name='person')
    op.drop_index('state', table_name='person')
    op.drop_index('zip_code', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('zip_code', 'person', ['zip_code'], unique=True)
    op.create_index('state', 'person', ['state'], unique=True)
    op.create_index('password', 'person', ['password'], unique=True)
    op.create_index('name', 'person', ['name'], unique=True)
    op.create_index('last_name', 'person', ['last_name'], unique=True)
    op.create_index('city', 'person', ['city'], unique=True)
    op.create_index('address', 'person', ['address'], unique=True)
    # ### end Alembic commands ###
