"""empty message

Revision ID: 646820be087e
Revises: 36a096817f64
Create Date: 2019-06-08 22:46:56.445200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646820be087e'
down_revision = '36a096817f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'person', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'email')
    # ### end Alembic commands ###
